apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-green
  labels:
    app: whoami-bg
    kubernetes.courselabs.co: deployments-ckad
  annotations:
    kubernetes.io/change-cause: "Green environment - version 2.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-bg
      environment: green
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: whoami-bg
        environment: green
        version: v2
    spec:
      containers:
      - name: app
        image: sixeyed/whoami:21.04.01
        env:
        - name: ENVIRONMENT
          value: "GREEN"
        - name: VERSION
          value: "2.0"
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
