# Exercise 1: Complete Secrets Workflow for CKAD
#
# Requirements:
# 1. Create an Opaque secret with database credentials
# 2. Create a TLS secret for HTTPS
# 3. Create a docker-registry secret for private images
# 4. Deploy a Pod that uses all three secrets:
#    - Database credentials as environment variables
#    - TLS certificate mounted as volume
#    - Private registry image using imagePullSecret
#
# Solution:

---
# Step 1: Create Opaque secret for database
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: webapp
    kubernetes.courselabs.co: secrets
type: Opaque
stringData:
  username: "appuser"
  password: "SecureDBPass123!"
  host: "postgres.production.svc.cluster.local"
  port: "5432"
  database: "production_db"
---
# Step 2: Create TLS secret (self-signed for testing)
apiVersion: v1
kind: Secret
metadata:
  name: webapp-tls
  labels:
    app: webapp
    kubernetes.courselabs.co: secrets
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICvDCCAaQCCQDyU/RYgzjIizANBgkqhkiG9w0BAQsFADAgMQ4wDAYDVQQDDAVs
    b2NhbDEPMA0GA1UECgwGU3RvcmUgQ0EwHhcNMjAwNDAxMDIzMzMwWhcNMjEwNDAx
    MDIzMzMwWjAgMQ4wDAYDVQQDDAVsb2NhbDEPMA0GA1UECgwGU3RvcmUgQ0EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDNTydX44YOFSX3rxRnf9zGelNx
    o4i3ulQqiXG3KwwT8DhhjLMBNHtl/6/I2Wo2Hz2Jwl6XBsYA+Qbu1ESgOet4TnfO
    Y1TFyjgWgxfCPBA9Gg9UZ1WsixDFl8CfFwG1mVCdSvIqSc3f/esrizt8hlFoQu28
    Cl0abn9Q8N/t5CH9crsB/e5eItOL1Ab9EqGedbBpMK6I54se3NiZGLdOl+AvCOgD
    SyGBhwsT8wdDxt3qaXck7JypCuLht5AvtHF3pVf/1k1Q9FxOQdjL+LsiiSr9lHbV
    TJLagHRftZN+qX1ockb+WVCh8Cdu6xCr7DqPoEp+gXkkWPeAkOfOZXedAgMBAAEw
    DQYJKoZIhvcNAQELBQADggEBACIeZIK9QYqxcOPh6Mkp+DSztSO7Xwzk0q5lyDHQ
    xeWzQYbLDpAlKFVe2RKIFyVaHzOONuHF+nvHJloiPyO3188/xdWLuz7JJ76IBqtG
    8lBkH1qvlGlHIFT3wSKJpEW5fYYC5nT8alAuN6RcYoGwFIpT2mKF7SLg7RXo8iqM
    oE5eiqqirpzS1MENuE5BzPeZJk3OXeWyypWHiIcwTfWPoyl30S2oOt5adLfmP2Dl
    NqStUs3oIsUTdSxSv72q5WZg+stJiRAR2cvjgZTShPmO9UTEW5CyidYbcgGLo0vC
    1Kd8qPqetnksTORt52JLXNwdkkdHcaaLujyiVQstThDcORc=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNTydX44YOFSX3
    rxRnf9zGelNxo4i3ulQqiXG3KwwT8DhhjLMBNHtl/6/I2Wo2Hz2Jwl6XBsYA+Qbu
    1ESgOet4TnfOY1TFyjgWgxfCPBA9Gg9UZ1WsixDFl8CfFwG1mVCdSvIqSc3f/esr
    izt8hlFoQu28Cl0abn9Q8N/t5CH9crsB/e5eItOL1Ab9EqGedbBpMK6I54se3NiZ
    GLdOl+AvCOgDSyGBhwsT8wdDxt3qaXck7JypCuLht5AvtHF3pVf/1k1Q9FxOQdjL
    +LsiiSr9lHbVTJLagHRftZN+qX1ockb+WVCh8Cdu6xCr7DqPoEp+gXkkWPeAkOfO
    ZXedAgMBAAECggEAFtZwfyYEblPdjjEr7hWFXmrpqZM6FXPJmP1w25CEQ5ozYHotc
    IsPpf4AADrEIBpyWkzvRY1aH+UFXF9xpOmLfOrfcb8KtG1ph7AG6yRgYcjiQygGd
    YsHgFJKKNktBEQCubkC5f/V5mb27QixsoRAjjz7IR475ux+KcHMCl3waqXLKFVyH
    Fs46UmmRW2Bi1Cnhd/IECAB02TYiQZViXoeLlCql8gNqZR3Xia+bi6q/+DV1KHVY
    uxWCzVO+83AOzpFjAWIVp7iYtl9jq+eNzjn23W59eXahZsDuNSlv9rd7+ecvud4L
    TEPpBxOnscwW8rKNNnl9NYIzp/HiigrqlBB6HQKBgQDMS5IyocW5crR5pNEQdlzB
    7xoBGt3V+F04fB7PGPd4JNI7ytgD+AVUiFfXGwgTEk8GPp+oLLtnEvH6+pLnUmuA
    sQdTVssRc0BAYBJg5SdgTbWFZ7jSKSMEWWXfJrCSUdb+BQpeGUXupVame4q70wMz
    iHGOe0Sd2l5id9noRRIQrwKBgQDV5E2KlPr8oawgC7Dm/1InEpUlJ18bf3wX2Gz/
    3F662D2GLdqic1LgpBxGNiGir6Cvr4IKHuVUzVxwBbsNQLUDzpyrbXwKYbWt5IH6
    ttL5dA4fABIPjvMt4GhVo/sPTSWVfLwgbYa+fKAfR+6yUwnU5ijCJ/UgMep0Obwr
    Z2Pnh6xUbQKBgQCm5qn9LX4xG5tgRUv8IOdoTw/9ngexjrGVEO5GghsJzviNQlWS
    O/esx+kqaVn2Kd1FxCUBjFl9gfOtY13KGjIg02XsjDt6AXYH6Q2DT+3/MaaKkF3x
    oYX3HAiol0cv7J7gF+DEidpW+KmEnVnLiImgLSVsae9zhacjnMa3VUVQnQKBgBhC
    gLPQM2jdj+WobmceqZNIj5B/ApFJYXfFt64uVOtpXZ2+hGC1AJqUsU27BtbXsoIp
    lMhX6BgItcvOzDKqtoqqbnUSNMQTaC0k0s6i9e+9valV8AQEZUJTsA8zwUysg+3s
    YggyNsIdqs4Y4jjWR9RZj9YFHVBo4EAwqVO8ho9hAoGAG29Qc4CkPd5K58ezDoyq
    RwS8FTKO6s/nAniK1BdFg/9sN/vEObyHXqcX3uh+c/0j4VhM5PX/s0sDNlTkbIQn
    o0xf2K5sW0EI1qCa/9ZkpiaY495mAeWehC3+3V9jWbf8BAce0XW3V/VXtTZnWow9
    XKhQisYQNvRg4Yq9lkUvD2k=
    -----END PRIVATE KEY-----
---
# Step 3: Create docker-registry secret
apiVersion: v1
kind: Secret
metadata:
  name: private-registry-cred
  labels:
    app: webapp
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.example.com": {
          "username": "deployment-user",
          "password": "registry-password-123",
          "email": "deploy@example.com",
          "auth": "ZGVwbG95bWVudC11c2VyOnJlZ2lzdHJ5LXBhc3N3b3JkLTEyMw=="
        }
      }
    }
---
# Step 4: Deploy Pod using all three secrets
apiVersion: v1
kind: Pod
metadata:
  name: webapp-complete
  labels:
    app: webapp
    kubernetes.courselabs.co: secrets
spec:
  # Use docker-registry secret for pulling private image
  imagePullSecrets:
  - name: private-registry-cred

  containers:
  - name: webapp
    image: registry.example.com/myorg/webapp:v1.0  # Private image
    ports:
    - containerPort: 8080
      name: http
    - containerPort: 8443
      name: https

    # Database credentials as environment variables
    env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: port
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: database
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password

    # TLS certificates mounted as files
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true

    command:
    - sh
    - -c
    - |
      echo "=== Web Application Starting ==="
      echo "Database: $DB_HOST:$DB_PORT/$DB_NAME"
      echo "User: $DB_USER"
      echo "TLS Certificate:"
      ls -la /etc/tls/
      echo ""
      echo "Starting HTTPS server with TLS..."
      echo "App would use /etc/tls/tls.crt and /etc/tls/tls.key"
      sleep 3600

  volumes:
  - name: tls-certs
    secret:
      secretName: webapp-tls

# Test commands:
# kubectl apply -f ex1-complete-secrets.yaml
# kubectl get secrets
# kubectl get pod webapp-complete
# kubectl logs webapp-complete
# kubectl exec webapp-complete -- ls -la /etc/tls/
# kubectl exec webapp-complete -- env | grep DB_
