# Example 1: Multiple deployments sharing a single PVC using subPath
# Use case: Multiple applications need their own directories on shared storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-app-storage
spec:
  accessModes:
    - ReadWriteOnce  # Note: Only one Pod can mount RWO at a time
  resources:
    requests:
      storage: 5Gi
---
# First deployment using subdirectory "app1"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1  # Only 1 replica since we're using RWO
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app
        image: nginx:alpine
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: app1  # Mounts only the "app1" subdirectory
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: shared-app-storage
---
# Second deployment using subdirectory "app2"
# Note: This would need ReadWriteMany to run simultaneously with app1
# For RWO, you'd typically scale down app1 first
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 0  # Start with 0 replicas due to RWO limitation
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app
        image: nginx:alpine
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: app2  # Mounts only the "app2" subdirectory
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: shared-app-storage
---
# Example 2: Mounting specific config files without hiding directory contents
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
data:
  app.conf: |
    server {
      listen 8080;
      root /usr/share/nginx/html;
    }
  logging.conf: |
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;
---
apiVersion: v1
kind: Pod
metadata:
  name: subpath-config-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    # Mount single file without hiding other files in /etc/nginx/conf.d/
    - name: config
      mountPath: /etc/nginx/conf.d/app.conf
      subPath: app.conf
    # Mount another file separately
    - name: config
      mountPath: /etc/nginx/conf.d/logging.conf
      subPath: logging.conf
  volumes:
  - name: config
    configMap:
      name: app-configs
---
# Example 3: Database with separate data and logs subdirectories
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: database-with-subpaths
spec:
  containers:
  - name: postgres
    image: postgres:14-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: "example"
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    volumeMounts:
    # Mount data directory to specific subPath
    - name: storage
      mountPath: /var/lib/postgresql/data
      subPath: data
    # Mount logs to different subPath on same PVC
    - name: storage
      mountPath: /var/log/postgresql
      subPath: logs
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: database-storage
---
# Example 4: Multi-tenant application using subPath for tenant isolation
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multi-tenant-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-tenant-app
  labels:
    app: multi-tenant
spec:
  containers:
  - name: tenant1-service
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Tenant 1 data" > /data/tenant1.txt
        ls -la /data
        sleep 3600
    volumeMounts:
    - name: storage
      mountPath: /data
      subPath: tenant1
  - name: tenant2-service
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Tenant 2 data" > /data/tenant2.txt
        ls -la /data
        sleep 3600
    volumeMounts:
    - name: storage
      mountPath: /data
      subPath: tenant2
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: multi-tenant-storage
---
# Example 5: Environment-specific subPath using subPathExpr
# Requires feature gate enabled (generally available in K8s 1.17+)
apiVersion: v1
kind: Pod
metadata:
  name: env-specific-subpath
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls -la /data && sleep 3600"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ENVIRONMENT
      value: "production"
    volumeMounts:
    - name: data
      mountPath: /data
      # subPathExpr uses environment variables
      subPathExpr: $(ENVIRONMENT)/$(POD_NAME)
  volumes:
  - name: data
    emptyDir: {}
