# Exists Operator Tolerations - CKAD Practice
#
# Tolerates any value for a given key (wildcard matching)

---
# Example 1: Tolerate any GPU taint value
apiVersion: v1
kind: Pod
metadata:
  name: gpu-flexible
  labels:
    app: gpu-app
spec:
  tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: app
    image: nvidia/cuda:11.0-base
    command: ["sh", "-c", "echo 'Running on GPU node (any type)'; sleep 3600"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"

---
# Example 2: Tolerate master/control-plane nodes
apiVersion: v1
kind: Pod
metadata:
  name: system-daemon
  labels:
    app: system-service
spec:
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: daemon
    image: busybox
    command: ["sh", "-c", "echo 'System daemon running'; sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"

---
# Example 3: Tolerate any maintenance taint
apiVersion: v1
kind: Pod
metadata:
  name: maintenance-tolerant
  labels:
    app: resilient-service
spec:
  tolerations:
  - key: "maintenance"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 600  # 10 minutes
  containers:
  - name: service
    image: nginx:alpine
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"

---
# Example 4: Deployment tolerating workload taints
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexible-deployment
  labels:
    app: flexible-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flexible-app
  template:
    metadata:
      labels:
        app: flexible-app
    spec:
      tolerations:
      - key: "workload"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "workload"
        operator: "Exists"
        effect: "PreferNoSchedule"
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"

---
# Example 5: Tolerate specific key with any effect
apiVersion: v1
kind: Pod
metadata:
  name: taint-effect-flexible
  labels:
    app: any-effect
spec:
  tolerations:
  - key: "special"
    operator: "Exists"
    # No effect specified - tolerates any effect (NoSchedule, PreferNoSchedule, NoExecute)
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo 'Tolerates special key with any effect'; sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"

---
# Example 6: DaemonSet with Exists tolerations
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-logger
  labels:
    app: logging
spec:
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: logger
        image: busybox
        command: ["sh", "-c", "while true; do echo Logging...; sleep 30; done"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"

---
# Example 7: Tolerate node condition taints
apiVersion: v1
kind: Pod
metadata:
  name: condition-tolerant
  labels:
    app: robust-app
spec:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "node.kubernetes.io/memory-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: app
    image: nginx:alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
