# Exact Match Tolerations - CKAD Practice
#
# These Pods tolerate specific taints using exact key=value matching

---
# Example 1: Tolerate GPU node taint
apiVersion: v1
kind: Pod
metadata:
  name: gpu-workload
  labels:
    app: ml-training
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.0-base
    command: ["sh", "-c", "echo 'GPU workload running'; sleep 3600"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"

---
# Example 2: Tolerate maintenance taint with NoExecute
apiVersion: v1
kind: Pod
metadata:
  name: critical-service
  labels:
    app: critical
    priority: high
spec:
  tolerations:
  - key: "maintenance"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
    tolerationSeconds: 300  # Stay for 5 minutes before eviction
  containers:
  - name: service
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"

---
# Example 3: Multiple exact tolerations
apiVersion: v1
kind: Pod
metadata:
  name: multi-toleration-pod
  labels:
    app: flexible-app
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  - key: "workload"
    operator: "Equal"
    value: "batch"
    effect: "PreferNoSchedule"
  - key: "environment"
    operator: "Equal"
    value: "testing"
    effect: "NoSchedule"
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo 'Running with multiple tolerations'; sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"

---
# Example 4: Deployment with exact toleration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-processor
  labels:
    app: batch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "batch"
        effect: "NoSchedule"
      containers:
      - name: processor
        image: busybox
        command: ["sh", "-c", "while true; do echo Processing...; sleep 10; done"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"

---
# Example 5: Tolerate control plane taint
apiVersion: v1
kind: Pod
metadata:
  name: control-plane-monitor
  labels:
    app: monitoring
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
  # Also tolerate legacy master taint
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
  containers:
  - name: monitor
    image: busybox
    command: ["sh", "-c", "echo 'Monitoring control plane'; sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"

---
# Example 6: Tolerate NoExecute without time limit
apiVersion: v1
kind: Pod
metadata:
  name: persistent-pod
  labels:
    app: persistent-service
spec:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Equal"
    value: ""
    effect: "NoExecute"
  - key: "node.kubernetes.io/not-ready"
    operator: "Equal"
    value: ""
    effect: "NoExecute"
  containers:
  - name: service
    image: nginx:alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
