apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-all-probes
  labels:
    app: whoami
    kubernetes.courselabs.co: deployments-ckad
  annotations:
    kubernetes.io/change-cause: "Deployment with all three probe types"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-all-probes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: whoami-all-probes
        version: v1
    spec:
      containers:
      - name: app
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

        # STARTUP PROBE: Runs first, protects slow-starting containers
        # Disables liveness checks until startup succeeds
        startupProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12      # Max 60s startup time (12 × 5s)

        # READINESS PROBE: Determines traffic eligibility
        # Only starts after startup probe succeeds
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 0    # Relies on startup probe
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3       # 3 failures = remove from endpoints

        # LIVENESS PROBE: Detects and restarts hung containers
        # Only starts after startup probe succeeds
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 0    # Relies on startup probe
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3       # 3 failures = restart container

      # Optional: demonstrate other probe types

      # TCP Socket probe example (useful for databases, TCP services)
      # livenessProbe:
      #   tcpSocket:
      #     port: 80
      #   initialDelaySeconds: 15
      #   periodSeconds: 10

      # Command execution probe example (useful for custom health checks)
      # livenessProbe:
      #   exec:
      #     command:
      #     - cat
      #     - /tmp/healthy
      #   initialDelaySeconds: 15
      #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-all-probes
  labels:
    kubernetes.courselabs.co: deployments-ckad
spec:
  type: NodePort
  selector:
    app: whoami-all-probes
  ports:
  - port: 80
    targetPort: http
    nodePort: 30023
