apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-multi
  labels:
    app: whoami
    kubernetes.courselabs.co: deployments-ckad
  annotations:
    kubernetes.io/change-cause: "Multi-container deployment with init and sidecar"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-multi
  template:
    metadata:
      labels:
        app: whoami-multi
        version: v1
    spec:
      # INIT CONTAINERS: Run sequentially before main containers
      initContainers:
      # Init 1: Verify dependencies
      - name: check-dependencies
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Checking system dependencies..."
          echo "DNS resolution: OK"
          echo "Network connectivity: OK"
          sleep 3
          echo "Dependencies verified!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"

      # Init 2: Setup shared data
      - name: setup-data
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Initializing shared data..."
          mkdir -p /shared-data/logs
          echo "Application started at $(date)" > /shared-data/startup.txt
          echo "Ready for application startup" > /shared-data/status.txt
          echo "Data setup complete!"
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"

      # MAIN CONTAINERS: All start together after init containers succeed
      containers:

      # Container 1: Main application
      - name: app
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ROLE
          value: "main-app"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10

      # Container 2: Monitoring sidecar
      - name: monitor
        image: busybox:1.36
        env:
        - name: ROLE
          value: "monitor"
        command:
        - sh
        - -c
        - |
          echo "Monitor sidecar started"
          # Read startup info from init container
          if [ -f /shared-data/startup.txt ]; then
            echo "Startup info:"
            cat /shared-data/startup.txt
          fi

          # Monitor main application
          while true; do
            echo "=== Health Check at $(date) ==="
            if [ -f /shared-data/status.txt ]; then
              cat /shared-data/status.txt
            fi
            echo "Application is running"
            sleep 30
          done
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"

      # Container 3: Log aggregator sidecar
      - name: log-aggregator
        image: busybox:1.36
        env:
        - name: ROLE
          value: "log-aggregator"
        command:
        - sh
        - -c
        - |
          echo "Log aggregator started"
          mkdir -p /shared-data/logs

          while true; do
            # Aggregate logs from shared volume
            echo "[$(date)] Aggregating logs..." >> /shared-data/logs/aggregated.log
            # In production: ship to centralized logging system
            sleep 45
          done
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"

      # Shared volumes
      volumes:
      - name: shared-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-multi
  labels:
    kubernetes.courselabs.co: deployments-ckad
spec:
  selector:
    app: whoami-multi
  ports:
  - port: 80
    targetPort: http
