apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-readiness
  labels:
    app: whoami
    kubernetes.courselabs.co: deployments-ckad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-readiness
  template:
    metadata:
      labels:
        app: whoami-readiness
        version: v1
    spec:
      containers:
      - name: app
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        # READINESS PROBE: Determines when Pod is ready to receive traffic
        # If probe fails, Pod is removed from Service endpoints (no traffic sent)
        # Use for: warm-up periods, dependency checks, temporary unavailability
        readinessProbe:
          # HTTP GET check - returns success if status code is 200-399
          httpGet:
            path: /           # Health check endpoint
            port: http        # Named port reference
            scheme: HTTP      # or HTTPS
            # Optional: add custom headers
            # httpHeaders:
            # - name: Custom-Header
            #   value: Health-Check

          initialDelaySeconds: 5    # Wait 5s after container starts
          periodSeconds: 5          # Check every 5 seconds
          timeoutSeconds: 3         # Wait 3s for response
          successThreshold: 1       # 1 success = ready
          failureThreshold: 3       # 3 failures = not ready
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-readiness
  labels:
    kubernetes.courselabs.co: deployments-ckad
spec:
  selector:
    app: whoami-readiness
  ports:
  - port: 80
    targetPort: http
  type: LoadBalancer
