apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-rolling
  labels:
    app: whoami
    kubernetes.courselabs.co: deployments
spec:
  replicas: 5
  selector:
    matchLabels:
      app: whoami
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # At most 1 extra pod during rollout
      maxUnavailable: 0  # All pods must be available (zero downtime)
  template:
    metadata:
      labels:
        app: whoami
        version: v1
    spec:
      containers:
      - name: app
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-rolling
  labels:
    kubernetes.courselabs.co: deployments
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
