apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-zero-downtime
  labels:
    app: webapp
    kubernetes.courselabs.co: deployments-ckad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-zero-downtime
  # Configure for zero-downtime updates
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # Create 1 extra pod during update
      maxUnavailable: 0     # Ensure all pods stay available
  template:
    metadata:
      labels:
        app: webapp-zero-downtime
        version: v1
    spec:
      containers:
      - name: app
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        # Readiness probe ensures traffic only goes to ready pods
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-zero-downtime
  labels:
    kubernetes.courselabs.co: deployments-ckad
spec:
  selector:
    app: webapp-zero-downtime
  ports:
  - port: 80
    targetPort: http
  type: LoadBalancer
