# Consuming Secrets - Environment Variables and Volume Mounts
# All methods for using Secrets in Pods

---
# Secret to use in examples
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque
stringData:
  database-username: "dbuser"
  database-password: "SecureP@ss123"
  api-key: "sk-1234567890abcdef"
  redis-password: "RedisP@ss456"
  jwt-secret: "my-jwt-secret-key"
---
# Method 1: Individual keys as environment variables
apiVersion: v1
kind: Pod
metadata:
  name: app-env-individual
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Individual Secret Keys as Env Vars ==="
      echo "Database User: $DB_USER"
      echo "Database Pass: [REDACTED]"
      echo "API Key: ${API_KEY:0:15}..."
      sleep 3600
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: database-username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: database-password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api-key
---
# Method 2: All keys as environment variables using envFrom
apiVersion: v1
kind: Pod
metadata:
  name: app-env-all
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== All Secret Keys as Env Vars ==="
      env | grep -E "(database-|api-key|redis-|jwt-)" | sed 's/=.*/=[REDACTED]/'
      echo ""
      echo "Database connection: $database-username@[REDACTED]"
      sleep 3600
    envFrom:
    - secretRef:
        name: app-secrets
---
# Method 3: Secret keys with custom env var names and prefix
apiVersion: v1
kind: Pod
metadata:
  name: app-env-prefix
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Secret Keys with Prefix ==="
      env | grep "^SECRET_" | sed 's/=.*/=[REDACTED]/'
      echo ""
      echo "Using: $SECRET_database-username"
      sleep 3600
    envFrom:
    - secretRef:
        name: app-secrets
      prefix: SECRET_  # All keys prefixed with "SECRET_"
---
# Method 4: Optional secret keys (won't fail if missing)
apiVersion: v1
kind: Pod
metadata:
  name: app-env-optional
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== With Optional Secret Keys ==="
      echo "Required API Key: ${API_KEY:0:10}..."
      echo "Optional Feature Flag: ${FEATURE_FLAG:-not set}"
      sleep 3600
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api-key
    - name: FEATURE_FLAG
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: non-existent-key  # Doesn't exist
          optional: true  # Pod starts anyway
---
# Method 5: Secret mounted as volume (all keys as files)
apiVersion: v1
kind: Pod
metadata:
  name: app-volume-all
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Secret Mounted as Volume ==="
      ls -la /secrets/
      echo ""
      echo "Database username:"
      cat /secrets/database-username
      echo ""
      echo "Files created for each secret key:"
      for file in /secrets/*; do
        echo "- $(basename $file)"
      done
      sleep 3600
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secrets
---
# Method 6: Selective secret keys mounted
apiVersion: v1
kind: Pod
metadata:
  name: app-volume-selective
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Selective Secret Keys Mounted ==="
      ls -la /secrets/
      echo ""
      cat /secrets/db-user
      sleep 3600
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secrets
      items:
      - key: database-username
        path: db-user  # Custom filename
      - key: database-password
        path: db-pass
        mode: 0400  # Read-only for owner only
---
# Method 7: Secret with subPath (single file)
apiVersion: v1
kind: Pod
metadata:
  name: app-volume-subpath
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: nginx:alpine
    volumeMounts:
    - name: api-key
      mountPath: /etc/app/api-key
      subPath: api-key
      readOnly: true
    command:
    - sh
    - -c
    - |
      echo "API Key file mounted:"
      cat /etc/app/api-key
      echo ""
      ls -la /etc/app/
      sleep 3600
  volumes:
  - name: api-key
    secret:
      secretName: app-secrets
---
# Method 8: Multiple secrets in same pod
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque
stringData:
  host: "postgres.example.com"
  port: "5432"
  database: "myapp"
---
apiVersion: v1
kind: Secret
metadata:
  name: cache-secrets
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque
stringData:
  redis-host: "redis.example.com"
  redis-port: "6379"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-multiple-secrets
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Multiple Secrets ==="
      echo "Database: $DB_HOST:$DB_PORT/$DB_NAME"
      echo "Cache: $REDIS_HOST:$REDIS_PORT"
      echo "Auth: [using mounted credentials]"
      cat /auth/database-password
      sleep 3600
    # Environment variables from multiple secrets
    env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: port
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: database
    - name: REDIS_HOST
      valueFrom:
        secretKeyRef:
          name: cache-secrets
          key: redis-host
    - name: REDIS_PORT
      valueFrom:
        secretKeyRef:
          name: cache-secrets
          key: redis-port
    # Volume mounts from another secret
    volumeMounts:
    - name: auth-secrets
      mountPath: /auth
      readOnly: true
  volumes:
  - name: auth-secrets
    secret:
      secretName: app-secrets
---
# Method 9: Secret with default permissions
apiVersion: v1
kind: Pod
metadata:
  name: app-volume-permissions
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Secret File Permissions ==="
      ls -la /secrets/
      stat /secrets/api-key
      sleep 3600
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secrets
      defaultMode: 0440  # r--r----- (owner and group can read)
      items:
      - key: api-key
        path: api-key
        mode: 0400  # r-------- (only owner can read)
---
# Method 10: Combining env vars and volumes from same secret
apiVersion: v1
kind: Pod
metadata:
  name: app-env-and-volume
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Secret as Both Env and Volume ==="
      echo "API Key (env): ${API_KEY:0:10}..."
      echo "JWT Secret (file):"
      cat /secrets/jwt-secret
      sleep 3600
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api-key
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secrets
      items:
      - key: jwt-secret
        path: jwt-secret
