# ImagePullSecrets - Using Secrets for Private Container Registries
# Essential for CKAD exam

---
# Docker Registry Secret (imperative command to create):
# kubectl create secret docker-registry regcred \
#   --docker-server=https://registry.example.com \
#   --docker-username=myuser \
#   --docker-password=mypassword \
#   --docker-email=user@example.com

# Declarative YAML format:
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
data:
  # .dockerconfigjson contains base64-encoded Docker config
  # Format: {"auths":{"registry.example.com":{"username":"user","password":"pass","email":"email","auth":"base64(user:pass)"}}}
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6Im15dXNlciIsInBhc3N3b3JkIjoibXlwYXNzd29yZCIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImF1dGgiOiJiWGwxYzJWeU9tMTVjR0Z6YzNkdmNtUT0ifX19
---
# Method 1: Using imagePullSecrets at Pod level
apiVersion: v1
kind: Pod
metadata:
  name: private-image-pod
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: registry.example.com/myapp:v1.0  # Private registry image
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: regcred  # Reference to docker-registry secret
---
# Method 2: Using imagePullSecrets in Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-image-deployment
  labels:
    kubernetes.courselabs.co: secrets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
      - name: app
        image: registry.example.com/myapp:v1.0
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
# Method 3: Multiple registry secrets
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "dockerhubuser",
          "password": "dockerhubpass",
          "auth": "ZG9ja2VyaHVidXNlcjpkb2NrZXJodWJwYXNz"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: gcr-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "gcr.io": {
          "username": "_json_key",
          "password": "{\"type\":\"service_account\",...}",
          "auth": "X2pzb25fa2V5Ont9"
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-registry-pod
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app1
    image: dockerhubuser/private-app:latest  # Docker Hub
  - name: app2
    image: gcr.io/project/private-app:latest  # Google Container Registry
  - name: app3
    image: registry.example.com/app:latest  # Custom registry
  imagePullSecrets:
  - name: docker-hub-secret
  - name: gcr-secret
  - name: regcred
---
# Method 4: ServiceAccount with imagePullSecrets (automatic)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  labels:
    kubernetes.courselabs.co: secrets
imagePullSecrets:
- name: regcred
- name: docker-hub-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa
  labels:
    kubernetes.courselabs.co: secrets
spec:
  serviceAccountName: my-service-account  # Automatically uses SA's imagePullSecrets
  containers:
  - name: app
    image: registry.example.com/myapp:v1.0
---
# Creating docker-registry secret with stringData (easier to read)
apiVersion: v1
kind: Secret
metadata:
  name: registry-readable
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.example.com": {
          "username": "myuser",
          "password": "mypassword",
          "email": "user@example.com",
          "auth": "bXl1c2VyOm15cGFzc3dvcmQ="
        }
      }
    }
---
# AWS ECR example (uses helper script for token)
apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "123456789012.dkr.ecr.us-west-2.amazonaws.com": {
          "username": "AWS",
          "password": "eyJwYXlsb2FkIjoi...",
          "auth": "QVdTOmV5SnBZWGxv..."
        }
      }
    }
---
# Azure Container Registry example
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "myregistry.azurecr.io": {
          "username": "myregistry",
          "password": "access-key-here",
          "auth": "bXlyZWdpc3RyeTphY2Nlc3Mta2V5LWhlcmU="
        }
      }
    }
---
# Troubleshooting: View decoded secret
# kubectl get secret regcred -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d | jq
apiVersion: v1
kind: Pod
metadata:
  name: debug-imagepull
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: debug
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Debugging ImagePullSecrets ==="
      echo "Checking if secret is mounted..."
      ls -la /var/run/secrets/
      sleep 3600
  imagePullSecrets:
  - name: regcred

# Common ImagePullBackOff issues:
# 1. Wrong credentials - verify username/password
# 2. Wrong registry URL - check https:// and registry domain
# 3. Secret not in same namespace as Pod
# 4. Image name doesn't match registry in secret
# 5. Registry requires authentication but no imagePullSecret specified
---
# Harbor Registry example (popular private registry)
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.example.com": {
          "username": "admin",
          "password": "Harbor12345",
          "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: harbor-app
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: harbor.example.com/library/myapp:latest
  imagePullSecrets:
  - name: harbor-secret
