# Secret Types - All Kubernetes Secret Types for CKAD
# Understanding different secret types and their use cases

---
# Type 1: Opaque (default) - Generic key-value pairs
apiVersion: v1
kind: Secret
metadata:
  name: opaque-secret
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque  # Default type for arbitrary data
data:
  # Values must be base64 encoded
  username: YWRtaW4=  # "admin"
  password: cGFzc3dvcmQxMjM=  # "password123"
stringData:
  # stringData automatically encodes to base64
  api-key: "my-secret-api-key-123"
  database-url: "postgresql://user:pass@db.example.com:5432/mydb"
---
# Type 2: kubernetes.io/dockerconfigjson - Docker registry credentials
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/dockerconfigjson
data:
  # .dockerconfigjson must contain base64-encoded Docker config
  # Generate with: kubectl create secret docker-registry ... --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzIiwiYXV0aCI6ImRYTmxjanB3WVhOeiJ9fX0=
---
# Type 3: kubernetes.io/tls - TLS certificate and key
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/tls
data:
  # tls.crt and tls.key are required keys for this type
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNVVENDQWJvQ0NRRHkwQlFLOHBqZHBEQU5CZ2txaGtpRzl3MEJBUXNGQURBM01Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1EwRXhGakFVQmdOVkJBY01EVk5oYmlCR2NtRnVZMmx6WTI4d0hoY05NakF3TXpBeQpNREF3TURBd1doY05NakV3TXpBeU1EQXdNREF3V2pBM01Rc3dDUVlEVlFRR0V3SlZVekVMTUFrR0ExVUVDQXdDClEwRXhGakFVQmdOVkJBY01EVk5oYmlCR2NtRnVZMmx6WTI4d2daOHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZMEEKTUlHSkFvR0JBTmJNS0R4SktZOGFGNzR4UXRwamRlK0Y4R1NQOGw1b1g4YktFZmFDM1pDcW5YZ1pXaUFuZ0ZHUQpkSW5GUDdzcXZGOVh4Q1lHWmlGQ2RQZnA5Nnh5RjNqWm5MVFZRS2J6UEdudDVuUEdNQmlOV2pBSlpJM0xrOVhsCmFvdEJQWjNZM2s4YnlMOUQwMzFBN3N5c1VQZUY4SzNFb2FWSDhleVl5SzRLTjRDWXVGNzFBZ01CQUFFd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdZRUFKaTBVaGViL1dqdXE5V3lRbmxMRVBzR0JGUjF0S3pVMjZGZnBnRW9UeHh3NApqeE1ydXQxSG94Y2hXQjBuUElnSDQzUDRBaFlEK2FlZktZYzhZVGYxUlhhbjczWjNKZzc1Y0ZibmdCRVZaV3l6CnFvcHpabWxvZHFIN1VjSHA0amJtdHJNSE1rNW0rMDBYQVc1MjVreFJTNU1HRkR1L25oRDBjNjBBbmRxZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUURXekNnOFNTbVBHaGUrTVVMYVkzWHZoZkJrai9KZWFGL0d5aEgyZ3QyUXFwMTRHVm9nCko0QlJrSFNKeFQrN0tyeGZWOFFtQm1ZaFFuVDM2ZmVzY2hkNDJaeTAxVUNtOHp4cDdlWnp4akFZalZvd0NXU04KeTVQVjVXcUxRVDJkMk41UEc4aS9ROU45UU83TXJGRDNoZkN0eEtHbFIvSHNtTWl1Q2plQW1MaGU5UUlEQVFBQgpBb0dBZE5nN0oxcUtyRzBjSFJTbk8rZjVKYUU4SEozVHZ4VzNGREdiUXVLRThYZHZzK0tJTE9FaTlMRzRsQmtUClloc0xQNTd6L0J2RXpZSFMyMzU3ZndHN2FPNmhPcnU3aEdCZ1VGYmZ3YXRqOGUycWh1YjlVcGtyWk5TVWtDam0KUDZHcFpJblFmbWM2dXhKeWw5YmFvTkVJZ2pQS2UxOTNyMjA2Wk1leGJ1Nmhva0VDUVFEMnpBSTN1NG9wQ3hwZgpqZU93WjRnYkFZUTJwTGtVVU9VOWRGYmpYY2E1WGxqd3NNSTJjRGcrbzdmbkpxZWFpUUI5Q0N0YzhZYWxvd3pXCkJzWDR0SkRaQWtFQTNvdGFnODBpYUQyUXY2TjBvb2JvOERqZGk4YkNrMjgvTjBBVCtFR1JZVFRBTjlzeUtGa3kKQlVaQjU3cUg4bjFRTERiWHcrRnJjQSs2K0ZacUxvcXVvUUpCQUpZcjJwdXBOcTJ3bWRGa0pHV1dneWQ3RXowUApoVWI3bzdDNy9hdlptbGlmV2x6b3BQOWhXajdaS3JBRm5PU1U3WXhCbXp5N1kyU0VoYjNVMWdhdGhna0NRRmhVCjdWOHZQdGR0NHdLN0phNE5qK1VXVm5Kal9Uc1lCSHFlRUt2ZUdlZ1pjaHZGQTNKQUNvN0dFSDh0M3VJMmRnQ0sKb1duRUlrYlhRTzh3eVdWd1pzRUNRRHRQUXYzcG1VZU5iVFJHekxaQm5RdVNJQUtTQ1hhc1RoSUxOQnFXdkNYSgpUbWdRMU9XekhjZTBxRnVxNUp1eWRhQU9HQ0xGdXRxUEVYL1BXdDBXOWlFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Type 4: kubernetes.io/service-account-token - Service account token (usually auto-created)
apiVersion: v1
kind: Secret
metadata:
  name: sa-token-secret
  labels:
    kubernetes.courselabs.co: secrets
  annotations:
    kubernetes.io/service-account.name: my-service-account
type: kubernetes.io/service-account-token
---
# Type 5: kubernetes.io/basic-auth - Basic authentication credentials
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: secretpassword123
---
# Type 6: kubernetes.io/ssh-auth - SSH authentication credentials
apiVersion: v1
kind: Secret
metadata:
  name: ssh-auth-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA... (truncated for brevity)
    -----END RSA PRIVATE KEY-----
---
# Type 7: bootstrap.kubernetes.io/token - Bootstrap token
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-abcdef
  namespace: kube-system
  labels:
    kubernetes.courselabs.co: secrets
type: bootstrap.kubernetes.io/token
stringData:
  token-id: abcdef
  token-secret: 0123456789abcdef
  description: "Bootstrap token for node joining"
  expiration: "2025-12-31T23:59:59Z"
  usage-bootstrap-authentication: "true"
  usage-bootstrap-signing: "true"
---
# Comparing data vs stringData
apiVersion: v1
kind: Secret
metadata:
  name: encoding-comparison
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque
data:
  # data: must be base64 encoded manually
  # echo -n "value1" | base64
  key1: dmFsdWUx  # "value1"
stringData:
  # stringData: automatically encoded to base64
  key2: value2  # Kubernetes encodes this
  key3: |
    Multi-line value
    Line 2
    Line 3

# After creation, all values in both data and stringData
# are stored as base64 in etcd
---
# Secret with immutable flag
apiVersion: v1
kind: Secret
metadata:
  name: immutable-secret
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque
immutable: true  # Cannot be updated after creation
stringData:
  critical-key: "this-cannot-be-changed"
  permanent-value: "immutable-data"
