# TLS Secrets and Certificate Management for CKAD
# Working with TLS certificates in Kubernetes

---
# Creating TLS secret imperatively:
# kubectl create secret tls my-tls-secret \
#   --cert=path/to/cert.pem \
#   --key=path/to/key.pem

# TLS Secret - kubernetes.io/tls type
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/tls
data:
  # tls.crt - Certificate (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2RENDQWFRQ0NRRHlVL1JZZ3pqSWl6QU5CZ2txaGtpRzl3MEJBUXNGQURBZ01RNHdEQVlEVlFRRERBVnMKYjJOaGJERVBNQTBHQTFVRUNnd0dVM1J2Y21VZ1EwRXdIaGNOTWpBd05EQXhNREl6TXpNd1doY05NakV3TkRBeApNREl6TXpNd1dqQWdNUTR3REFZRFZRUUREQVZzYjJOaGJERVBNQTBHQTFVRUNnd0dVM1J2Y21VZ1EwRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRE5UeWRYNDRZT0ZJWDNyeFJuZjl6R2VsTngKbzRpM3VsUXFpWEczS3d3VDhEaGhqTE1CTkh0bC82L0kyV28ySHoySndsNlhCc1lBK1FidTFFU2dPZXQ0VG5mTwpZMVRGeWpnV2d4ZkNQQkE5R2c5VVoxV3NpeERGbDhDZkZ3RzFtVkNkU3ZJcVNjM2YvZXNyaXp0OGhsRm9RdTI4CkNsMGFibjlROE4vdDVDSDljcnNCL2U1ZUl0T0wxQWI5RXFHZWJkQnBNSzZJNTRzZTNOaVpHTGRPbCtBdkNPZ0QKU3lHQmh3c1Q4d2REeHQzcWFYY2s3SnlwQ3VMaHQ1QXZ0SEYzcFZmLzFrMVE5RnhPUWRqTCtMc2lpU3I5bEhiVgpUSkxhZ0hSZnRaTitxWDFvY2tiK1dWQ2g4Q2R1NnhDcjdEcVBvRXArZ1hra1dQZUFrT2ZPWlhlZEFnTUJBQUV3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDSWVaSUs5UVlxeGNPUGg2TWtwK0RTenRTTzdYd3prMHE1bHlESFEKeGVXelFZYkxEcEFsS0ZWZTJSS0lGeVZhSHpPT051SEYrbnZISmxvaVB5TzM5MTgveGRXTHV6N0pKNzZJQnF0Zwo4bEJrSDFxdmxHbEhJRlQzd1NLSnBFVzVmWVlDNW5UOGFsQXVONlJjWW9Hd0ZJcFQybUtGN1NMZzdSWG84aXFNCm9FNWVpcXFpcnB6UzFNRU51RTVCelBlWkprM09YZVd5eXBXSGlJY3dUZldQb3lsMzBTMm9PdDVhZExmbVAyRGwKTnFTdFVzM29Jc1VUZFN4U3Y3MnE1V1pnK3N0SmlSQVIyY3ZqZ1pUU2hQbU85VVRFVzVDeWlkWWJjZ0dMbzB2QwoxS2Q4cVBxZXRua3NUT1J0NTJKTFhOd2Rra2RIY2FhTHVqeWlWUXN0VGhEY09SYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  # tls.key - Private key (base64 encoded)
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRE5UeWRYNDRZT0ZJWDMKcnhSbmY5ekdlbE54bzRpM3VsUXFpWEczS3d3VDhEaGhqTE1CTkh0bC82L0kyV28ySHoySndsNlhCc1lBK1FidQoxRVNnT2V0NFRuZk9ZMVRGeWpnV2d4ZkNQQkE5R2c5VVoxV3NpeERGbDhDZkZ3RzFtVkNkU3ZJcVNjM2YvZXNyCml6dDhobEZvUXUyOENsMGFibjlROE4vdDVDSDljcnNCL2U1ZUl0T0wxQWI5RXFHZWJkQnBNSzZJNTRzZTNOaVoKR0xkT2wrQXZDT2dEU3lHQmh3c1Q4d2REeHQzcWFYY2s3SnlwQ3VMaHQ1QXZ0SEYzcFZmLzFrMVE5RnhPUWRqTAorTHNpaVNyOWxIYlZUSkxhZ0hSZnRaTitxWDFvY2tiK1dWQ2g4Q2R1NnhDcjdEcVBvRXArZ1hra1dQZUFrT2ZPClpYZWRBZ01CQUFFQ2dnRUFGdFp3ZnlZRWJsUGRqakVyN2hXRlhtcnBxWk02RlhQSlAxdzI1Q0VENW96WUhvdGMKSXNQcGY0QUFEckVJQnB5V2t6dlJZMWFIK1VGWEY5eHBPbUxmT3JmY2I4S3RHMXBoN0FHNnlSZ1ljamlReWdHZApZc0hnRkpLS05rdEJFUUN1YmtDNWYvVjVtYjI3UWl4c29SQWpqejdJUjQ3NXV4K0tjSE1DbDN3YXFYTEtGVnlICkZzNDZVbW1SVzJCaTFDbmhkL0lFQ0FCMDJUWWlRWlZpWG9lTGxDcWw4Z05xWlIzWGlhK2JpNnEvK0RWMUtIVlkKdXhXQ3pWTys4M0FPenBGakFXSVZwN2lZdGw5anErZU56am4yM1c1OWVYYWhac0R1TlNsdjlyZDcrZWN2dWQ0TApURVBwQnhPbnNjd1c4cktOTm5sOU5ZSXpwL0hpaWdycWxCQjZIUUtCZ1FETVM1SXlvY1c1Y3JSNXBORVFkbHpCCjd4b0JHdDNWK0YwNGZCN1BHUGQ0Sk5JN3l0Z0QrQVZVaUZmWEd3Z1RFazhHUHArb0xMdG5Fdkg2K3BMblVtdUEKc1FkVFZzc1JjMEJBWUJKZzVTZGdUYldGWjdqU0tTTUVXV1hmSnJDU1VkYitCUXBlR1VYdXBWYW1lNHE3MHdNeAppSEdPZTBTZDJsNWlkOW5vUlJJUXJ3S0JnUURWNUUyS2xQcjhvYXdnQzdEbS8xSW5FcFVsSjE4YmYzd1gyR3ovCjNGNjYyRDJHTGRxaWMxTGdwQnhHTmlHaXI2Q3ZyNElLSHVWVXpWeHdCYnNOUUxVRHpweXJiWHdLWWJXdDVJSDYKdHRMNWRBNGZBQklQanZNdDRHaFZvL3NQVFNXVmZMd2diWWErZktBZlIrNnlVd25VNWlqQ0ovVWdNZXAwT2J3cgpaMlBuaDZ4VWJRS0JnUUNtNXFuOUxYNHhHNXRnUlV2OElPZG9Udy85bmdleGpyR1ZFTzVHZ2hzSnp2aU5RbFdTCk8vZXN4K2txYVZuMktkMUZ4Q1VCakZsOWdmT3RZMTNLR2pJZzAyWHNqRHQ2QVhZSDZRMkRUKzMvTWFhS2tGM3gKb1lYM0hBaW9sMGN2N0o3Z0YrREVpZHBXK0ttRW5WbkxpSW1nTFNWc2FlOXpoYWNqbk1hM1ZVVlFuUUtCZ0JoQwpnTFBRTTJqZGorV29ibWNlNVpOSWo1Qi9BcEZKWVhmRnQ2NHVWT3RwWFoyK2hHQzFBSnFVc1UyN0J0Ylhzb0lwCmxNaFg2QmdJdGN2T3pES3F0b3FxYm5VU05NUVRhQzBrMHM2aTllKzl2YWxWOEFRRVpVSlRzQTh6d1V5c2crM3MKWWdneU5zSWRxczRZNGpqV1I5UlpqOVlGSFZCbzRFQXdxVk84aG85aEFvR0FHMjlRYzRDa1BkNUs1OGV6RG95bwpSd1M4RlRLTzZzL25BbmlLMUJkRmcvOXNOL3ZFT2J5SFhxY1gzdWgrYy8wajRWaE01UFgvczBzRE5sVGtiSVFuCm8weGYySzVzVzBFSTFxQ2EvOVprcGlhWTQ5NW1BZVdlaEMzKzNWOWpXYmY4QkFjZTBYVzNWL1ZYdFRabldvdzkKWEtoUWlzWVFOdlJnNFlxOWxrVXZEMms9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
# Using TLS Secret in Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress
  labels:
    kubernetes.courselabs.co: secrets
spec:
  tls:
  - hosts:
    - example.com
    - www.example.com
    secretName: tls-secret  # Reference to TLS secret
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
---
# Multiple TLS certificates for different domains
apiVersion: v1
kind: Secret
metadata:
  name: tls-app1
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICvDCCAaQCCQDyU/RYgzjIizANBgkqhkiG9w0BAQsFADAgMQ4wDAYDVQQDDAVs
    ...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNTydX44YOFSX3
    ...
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-app2
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICvDCCAaQCCQDyU/RYgzjIizANBgkqhkiG9w0BAQsFADAgMQ4wDAYDVQQDDAVs
    ...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNTydX44YOFSX3
    ...
    -----END PRIVATE KEY-----
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-tls-ingress
  labels:
    kubernetes.courselabs.co: secrets
spec:
  tls:
  - hosts:
    - app1.example.com
    secretName: tls-app1
  - hosts:
    - app2.example.com
    secretName: tls-app2
  rules:
  - host: app1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-service
            port:
              number: 80
  - host: app2.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2-service
            port:
              number: 80
---
# Using TLS in Pod (mTLS - mutual TLS)
apiVersion: v1
kind: Pod
metadata:
  name: mtls-client
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: client
    image: curlimages/curl:latest
    command:
    - sh
    - -c
    - |
      echo "Making mTLS request..."
      curl --cert /certs/tls.crt \
           --key /certs/tls.key \
           --cacert /certs/ca.crt \
           https://secure-api.example.com
      sleep 3600
    volumeMounts:
    - name: client-certs
      mountPath: /certs
      readOnly: true
  volumes:
  - name: client-certs
    secret:
      secretName: tls-secret
---
# Self-signed certificate creation (for testing)
# Commands to create:
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#   -keyout tls.key -out tls.crt \
#   -subj "/CN=example.com/O=example"
# kubectl create secret tls self-signed-tls --cert=tls.crt --key=tls.key

apiVersion: v1
kind: Secret
metadata:
  name: self-signed-tls
  labels:
    kubernetes.courselabs.co: secrets
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICvDCCAaQCCQDyU/RYgzjIizANBgkqhkiG9w0BAQsFADAgMQ4wDAYDVQQDDAVs
    b2NhbDEPMA0GA1UECgwGU3RvcmUgQ0EwHhcNMjAwNDAxMDIzMzMwWhcNMjEwNDAx
    MDIzMzMwWjAgMQ4wDAYDVQQDDAVsb2NhbDEPMA0GA1UECgwGU3RvcmUgQ0EwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDNTydX44YOFSX3rxRnf9zGelNx
    o4i3ulQqiXG3KwwT8DhhjLMBNHtl/6/I2Wo2Hz2Jwl6XBsYA+Qbu1ESgOet4TnfO
    Y1TFyjgWgxfCPBA9Gg9UZ1WsixDFl8CfFwG1mVCdSvIqSc3f/esrizt8hlFoQu28
    Cl0abn9Q8N/t5CH9crsB/e5eItOL1Ab9EqGedbBpMK6I54se3NiZGLdOl+AvCOgD
    SyGBhwsT8wdDxt3qaXck7JypCuLht5AvtHF3pVf/1k1Q9FxOQdjL+LsiiSr9lHbV
    TJLagHRftZN+qX1ockb+WVCh8Cdu6xCr7DqPoEp+gXkkWPeAkOfOZXedAgMBAAEw
    DQYJKoZIhvcNAQELBQADggEBACIeZIK9QYqxcOPh6Mkp+DSztSO7Xwzk0q5lyDHQ
    xeWzQYbLDpAlKFVe2RKIFyVaHzOONuHF+nvHJloiPyO39188/xdWLuz7JJ76IBqtG
    8lBkH1qvlGlHIFT3wSKJpEW5fYYC5nT8alAuN6RcYoGwFIpT2mKF7SLg7RXo8iqM
    oE5eiqqirpzS1MENuE5BzPeZJk3OXeWyypWHiIcwTfWPoyl30S2oOt5adLfmP2Dl
    NqStUs3oIsUTdSxSv72q5WZg+stJiRAR2cvjgZTShPmO9UTEW5CyidYbcgGLo0vC
    1Kd8qPqetnksTORt52JLXNwdkkdHcaaLujyiVQstThDcORc=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNTydX44YOFSX3
    rxRnf9zGelNxo4i3ulQqiXG3KwwT8DhhjLMBNHtl/6/I2Wo2Hz2Jwl6XBsYA+Qbu
    1ESgOet4TnfOY1TFyjgWgxfCPBA9Gg9UZ1WsixDFl8CfFwG1mVCdSvIqSc3f/esr
    izt8hlFoQu28Cl0abn9Q8N/t5CH9crsB/e5eItOL1Ab9EqGedbBpMK6I54se3NiZ
    GLdOl+AvCOgDSyGBhwsT8wdDxt3qaXck7JypCuLht5AvtHF3pVf/1k1Q9FxOQdjL
    +LsiiSr9lHbVTJLagHRftZN+qX1ockb+WVCh8Cdu6xCr7DqPoEp+gXkkWPeAkOfO
    ZXedAgMBAAECggEAFtZwfyYEblPdjjEr7hWFXmrpqZM6FXPJmP1w25CEQ5ozYHotc
    IsPpf4AADrEIBpyWkzvRY1aH+UFXF9xpOmLfOrfcb8KtG1ph7AG6yRgYcjiQygGd
    YsHgFJKKNktBEQCubkC5f/V5mb27QixsoRAjjz7IR475ux+KcHMCl3waqXLKFVyH
    Fs46UmmRW2Bi1Cnhd/IECAB02TYiQZViXoeLlCql8gNqZR3Xia+bi6q/+DV1KHVY
    uxWCzVO+83AOzpFjAWIVp7iYtl9jq+eNzjn23W59eXahZsDuNSlv9rd7+ecvud4L
    TEPpBxOnscwW8rKNNnl9NYIzp/HiigrqlBB6HQKBgQDMS5IyocW5crR5pNEQdlzB
    7xoBGt3V+F04fB7PGPd4JNI7ytgD+AVUiFfXGwgTEk8GPp+oLLtnEvH6+pLnUmuA
    sQdTVssRc0BAYBJg5SdgTbWFZ7jSKSMEWWXfJrCSUdb+BQpeGUXupVame4q70wMz
    iHGOe0Sd2l5id9noRRIQrwKBgQDV5E2KlPr8oawgC7Dm/1InEpUlJ18bf3wX2Gz/
    3F662D2GLdqic1LgpBxGNiGir6Cvr4IKHuVUzVxwBbsNQLUDzpyrbXwKYbWt5IH6
    ttL5dA4fABIPjvMt4GhVo/sPTSWVfLwgbYa+fKAfR+6yUwnU5ijCJ/UgMep0Obwr
    Z2Pnh6xUbQKBgQCm5qn9LX4xG5tgRUv8IOdoTw/9ngexjrGVEO5GghsJzviNQlWS
    O/esx+kqaVn2Kd1FxCUBjFl9gfOtY13KGjIg02XsjDt6AXYH6Q2DT+3/MaaKkF3x
    oYX3HAiol0cv7J7gF+DEidpW+KmEnVnLiImgLSVsae9zhacjnMa3VUVQnQKBgBhC
    gLPQM2jdj+WobmceqZNIj5B/ApFJYXfFt64uVOtpXZ2+hGC1AJqUsU27BtbXsoIp
    lMhX6BgItcvOzDKqtoqqbnUSNMQTaC0k0s6i9e+9valV8AQEZUJTsA8zwUysg+3s
    YggyNsIdqs4Y4jjWR9RZj9YFHVBo4EAwqVO8ho9hAoGAG29Qc4CkPd5K58ezDoyq
    RwS8FTKO6s/nAniK1BdFg/9sN/vEObyHXqcX3uh+c/0j4VhM5PX/s0sDNlTkbIQn
    o0xf2K5sW0EI1qCa/9ZkpiaY495mAeWehC3+3V9jWbf8BAce0XW3V/VXtTZnWow9
    XKhQisYQNvRg4Yq9lkUvD2k=
    -----END PRIVATE KEY-----
---
# CA Certificate Secret (for verifying server certificates)
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-secret
  labels:
    kubernetes.courselabs.co: secrets
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICvDCCAaQCCQDyU/RYgzjIizANBgkqhkiG9w0BAQsFADAgMQ4wDAYDVQQDDAVs
    ...
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Pod
metadata:
  name: app-with-ca
  labels:
    kubernetes.courselabs.co: secrets
spec:
  containers:
  - name: app
    image: curlimages/curl:latest
    command:
    - sh
    - -c
    - |
      echo "Using custom CA certificate..."
      curl --cacert /ca/ca.crt https://internal-api.example.com
      sleep 3600
    volumeMounts:
    - name: ca-cert
      mountPath: /ca
      readOnly: true
  volumes:
  - name: ca-cert
    secret:
      secretName: ca-cert-secret
