apiVersion: db.example.com/v1
kind: Database
metadata:
  name: cache-redis
  namespace: default
  labels:
    environment: production
    team: platform
spec:
  engine: redis
  version: "7.0"
  storageSize: 5Gi
  replicas: 2
