apiVersion: postgres.example.com/v1
kind: PostgresCluster
metadata:
  name: production-db
  namespace: default
  labels:
    environment: production
    app: postgres
spec:
  version: "15"
  replicas: 3
  storage:
    size: 100Gi
    storageClass: fast-ssd
  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: 7
  monitoring:
    enabled: true
