apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-operator
  namespace: default
  labels:
    app: webapp-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-operator
  labels:
    app: webapp-operator
rules:
# Watch and manage WebApp custom resources
- apiGroups: ["apps.example.com"]
  resources: ["webapps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Update status subresource
- apiGroups: ["apps.example.com"]
  resources: ["webapps/status"]
  verbs: ["get", "update", "patch"]
# Update scale subresource
- apiGroups: ["apps.example.com"]
  resources: ["webapps/scale"]
  verbs: ["get", "update", "patch"]
# Manage Deployments created by operator
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Manage Services created by operator
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Manage ConfigMaps for app configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Manage Secrets for credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Read Pods to check status
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Create Events for operator activities
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webapp-operator
  labels:
    app: webapp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webapp-operator
subjects:
- kind: ServiceAccount
  name: webapp-operator
  namespace: default
