# Example TLS Secret structure
# In practice, create TLS secrets using:
#   kubectl create secret tls <name> --cert=<cert-file> --key=<key-file>

# This is what the secret looks like (base64 encoded):
apiVersion: v1
kind: Secret
metadata:
  name: example-tls
  namespace: default
  labels:
    kubernetes.courselabs.co: ingress
type: kubernetes.io/tls
data:
  # tls.crt: <base64-encoded-certificate>
  # tls.key: <base64-encoded-private-key>
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3hNREV3TXpBeU1Gb1hEVEl5TURneE1ERXdNekF5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmRZCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFhXR01hRGVHaTFPOXAKZGhZdVRzK2dnRjBYVzJoQ3F2S1FrZ1FUNjBGVzJGVzJoQ3F2S1FrZ1FUNjBGVzJGVzJoQ3F2S1FrZ1FUNjBGVwoyRlcyaENxdktRa2dRVDYwRlcyRlcyaENxdktRa2dRVDYwRlcyRlcyaENxdktRa2dRVDYwRlcyRlcyaENxdksK
---
# Commands to create TLS secrets:

# From PEM files:
# kubectl create secret tls myapp-tls --cert=myapp.crt --key=myapp.key

# From PEM files in a specific namespace:
# kubectl create secret tls myapp-tls --cert=myapp.crt --key=myapp.key -n my-namespace

# Verify the secret:
# kubectl get secret myapp-tls -o yaml
# kubectl describe secret myapp-tls

# View certificate details:
# kubectl get secret myapp-tls -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -text -noout
