apiVersion: v1
kind: Namespace
metadata:
  name: exercise1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: exercise1
data:
  database_url: "postgres://db.example.com:5432"
  api_key: "config-api-key-123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: exercise1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp  # PROBLEM: Label mismatch - pods are labeled 'web'
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_url  # PROBLEM: Wrong key - should be database_url
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: exercise1
spec:
  selector:
    app: web
  ports:
  - port: 8080      # PROBLEM: Port mismatch
    targetPort: 80  # Service expects 8080 but container uses 80
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: exercise1
spec:
  hard:
    requests.cpu: "100m"    # PROBLEM: Too low for deployment
    requests.memory: "100Mi"
    limits.cpu: "200m"
    limits.memory: "200Mi"
