apiVersion: v1
kind: Namespace
metadata:
  name: limitrange-test
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: limitrange-test
spec:
  limits:
  - max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
---
# This pod will fail - exceeds LimitRange max
apiVersion: v1
kind: Pod
metadata:
  name: limitrange-exceeded
  namespace: limitrange-test
  labels:
    app: troubleshooting-demo
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "2Gi"  # Exceeds max of 1Gi
        cpu: "2"       # Exceeds max of 1
      limits:
        memory: "2Gi"
        cpu: "2"
