apiVersion: v1
kind: Pod
metadata:
  name: memory-leak
  labels:
    app: troubleshooting-demo
    scenario: performance
spec:
  containers:
  - name: leaky-app
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - |
      # Simulate memory leak by allocating memory continuously
      apt-get update && apt-get install -y stress-ng
      stress-ng --vm 1 --vm-bytes 200M --vm-hang 0 --timeout 300s
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"  # Will be exceeded and cause OOMKilled
