apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debugger
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: myapp
            tier: backend
        topologyKey: kubernetes.io/hostname

  containers:
  - name: debug
    image: busybox
    command: ['sh', '-c']
    args:
    - |
      echo "Debug pod started"
      echo "This pod is co-located with DaemonSet pod"
      echo "Can access shared HostPath volume"

      # Access shared volume
      ls -la /shared || echo "Shared volume not mounted"

      # Verify we're on same node as DaemonSet pod
      echo ""
      echo "Node: ${NODE_NAME}"

      # Keep running for debugging
      sleep 3600
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - name: shared-data
      mountPath: /shared

  volumes:
  - name: shared-data
    hostPath:
      path: /tmp/shared-data
      type: DirectoryOrCreate
