apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-daemonset
  labels:
    app: myapp
    tier: backend
spec:
  selector:
    matchLabels:
      app: myapp
      tier: backend
  template:
    metadata:
      labels:
        app: myapp
        tier: backend
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

      volumes:
      - name: shared-data
        hostPath:
          path: /tmp/shared-data
          type: DirectoryOrCreate
