apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controlled-rollout
  labels:
    app: controlled-rollout
    exercise: ex2
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: controlled-rollout
  template:
    metadata:
      labels:
        app: controlled-rollout
        version: v1
    spec:
      containers:
      - name: app
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "1.0"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ['sh', '-c']
        args:
        - |
          echo "<h1>Version ${VERSION}</h1><p>Node: ${NODE_NAME}</p>" > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
