apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
  labels:
    app: ssd-monitor
    exercise: ex3
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector:
        disktype: ssd
      containers:
      - name: monitor
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "SSD monitor on ${NODE_NAME}"
          while true; do
            echo "$(date): Monitoring SSD storage on ${NODE_NAME}"
            sleep 30
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
