apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prod-monitor
  labels:
    app: monitor
    env: production
    exercise: ex3
spec:
  selector:
    matchLabels:
      app: monitor
      env: production
  template:
    metadata:
      labels:
        app: monitor
        env: production
    spec:
      nodeSelector:
        env: production
      containers:
      - name: monitor
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "Production monitor on ${NODE_NAME}"
          while true; do
            echo "$(date): Monitoring production node ${NODE_NAME}"
            sleep 30
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
