apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: all-nodes-monitor
  labels:
    app: all-nodes-monitor
    exercise: ex3
spec:
  selector:
    matchLabels:
      app: all-nodes-monitor
  template:
    metadata:
      labels:
        app: all-nodes-monitor
    spec:
      tolerations:
      # Run on master/control-plane nodes
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      # Tolerate all taints
      - operator: Exists
      containers:
      - name: monitor
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "All-nodes monitor on ${NODE_NAME}"
          echo "Running on ALL nodes including master/control-plane"
          while true; do
            echo "$(date): Monitoring ${NODE_NAME}"
            sleep 30
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
