apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-with-init
  labels:
    app: app-with-init
spec:
  selector:
    matchLabels:
      app: app-with-init
  template:
    metadata:
      labels:
        app: app-with-init
    spec:
      initContainers:
      # Init container 1: Create directory structure
      - name: setup-directories
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "Setting up directories..."
          mkdir -p /data/logs /data/config /data/cache
          echo "Directories created successfully"
        volumeMounts:
        - name: data
          mountPath: /data

      # Init container 2: Download configuration
      - name: fetch-config
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "Fetching configuration..."
          cat > /config/app.conf <<EOF
          NODE_NAME=${NODE_NAME}
          POD_NAME=${POD_NAME}
          POD_IP=${POD_IP}
          NAMESPACE=${NAMESPACE}
          EOF
          echo "Configuration created at /config/app.conf"
          cat /config/app.conf
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /config

      # Init container 3: Set permissions
      - name: set-permissions
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "Setting permissions..."
          chmod -R 755 /data
          echo "Permissions set successfully"
          ls -la /data
        volumeMounts:
        - name: data
          mountPath: /data

      containers:
      - name: app
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "Application starting..."
          echo "Reading configuration from /etc/app/app.conf:"
          cat /etc/app/app.conf
          echo ""
          echo "Data directory contents:"
          ls -la /var/app/data
          echo ""
          echo "Application running on ${NODE_NAME}"
          while true; do
            echo "$(date): App running on ${NODE_NAME}" >> /var/app/data/logs/app.log
            sleep 30
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /etc/app
          readOnly: true
        - name: data
          mountPath: /var/app/data
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"

      volumes:
      - name: config
        emptyDir: {}
      - name: data
        emptyDir: {}
