apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  labels:
    app: log-collector
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: collector
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "Log collector starting..."
          echo "Node: ${NODE_NAME}"
          echo "Collecting logs from /var/log (read-only)"

          # Tail log files and output to stdout
          while true; do
            echo "=== $(date) ==="
            # Count log files
            find /var/log -type f 2>/dev/null | wc -l || echo "Cannot count logs"
            # Show recent entries (if permissions allow)
            tail -n 5 /var/log/*.log 2>/dev/null || echo "Limited log access (expected with security context)"
            sleep 60
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true  # Read-only access
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true  # Read-only access

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
          type: DirectoryOrCreate
