apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: system-monitor
  labels:
    app: system-monitor
spec:
  selector:
    matchLabels:
      app: system-monitor
  template:
    metadata:
      labels:
        app: system-monitor
    spec:
      tolerations:
      # Tolerate master/control-plane nodes
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      # Tolerate not-ready and unreachable nodes
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 300
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 300
      containers:
      - name: monitor
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          echo "System monitor running on $(hostname)"
          echo "Node: ${NODE_NAME}"
          while true; do
            echo "$(date): Monitoring node ${NODE_NAME}"
            sleep 30
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
