apiVersion: v1
kind: Service
metadata:
  name: required-service
spec:
  selector:
    app: dummy
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-backend
  labels:
    app: dummy
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
