apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger-ondelete
  labels:
    app: logger
    strategy: ondelete
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: logger
      strategy: ondelete
  template:
    metadata:
      labels:
        app: logger
        strategy: ondelete
    spec:
      containers:
      - name: logger
        image: busybox:1.35
        command: ['sh', '-c', 'echo "Version 1.0 - OnDelete" && sleep 3600']
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
