apiVersion: v1
kind: Pod
metadata:
  name: app-with-adapter
  labels:
    app: legacy-app
    pattern: adapter
    kubernetes.courselabs.co: pods
spec:
  containers:
  - name: legacy-app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      # Application outputs logs in custom format
      echo "Legacy app started"
      while true; do
        timestamp=$(date +%s)
        echo "[$timestamp] CUSTOM_LOG: event=user_login,user=alice,status=success" >> /logs/app.log
        sleep 5
        echo "[$timestamp] CUSTOM_LOG: event=api_call,endpoint=/users,duration=150ms" >> /logs/app.log
        sleep 5
      done
    volumeMounts:
    - name: log-volume
      mountPath: /logs
  - name: log-adapter
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Log adapter started - converting logs to standard JSON format"
      while true; do
        if [ -f /logs/app.log ]; then
          tail -f /logs/app.log | while read line; do
            # Adapter transforms custom format to JSON
            timestamp=$(echo $line | grep -o '\[.*\]' | tr -d '[]')
            event=$(echo $line | grep -o 'event=[^,]*' | cut -d= -f2)
            echo "{\"timestamp\":\"$timestamp\",\"event\":\"$event\",\"original\":\"$line\"}" >> /logs/standardized.log
          done
        fi
        sleep 1
      done
    volumeMounts:
    - name: log-volume
      mountPath: /logs
  volumes:
  - name: log-volume
    emptyDir: {}
