apiVersion: v1
kind: Pod
metadata:
  name: app-wait-for-service
  labels:
    app: myapp
    kubernetes.courselabs.co: pods
spec:
  initContainers:
  - name: wait-for-database
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Waiting for database service to be available..."
      until nslookup database-service.default.svc.cluster.local; do
        echo "Database service not ready, waiting..."
        sleep 2
      done
      echo "Database service is available!"
  - name: wait-for-api
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Waiting for API service to respond..."
      until wget -q -O- http://api-service:8080/health; do
        echo "API service not ready, waiting..."
        sleep 2
      done
      echo "API service is ready!"
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80
---
# Example service that the init container waits for
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    kubernetes.courselabs.co: pods
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    kubernetes.courselabs.co: pods
spec:
  selector:
    app: api
  ports:
  - port: 8080
    targetPort: 8080
