apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
  labels:
    app: myapp
    kubernetes.courselabs.co: pods
spec:
  initContainers:
  - name: init-database
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Running database migrations..."
      # Simulate database setup
      sleep 3
      echo "Database migration completed"
      echo "Database ready" > /config/db-status
    volumeMounts:
    - name: config
      mountPath: /config
  - name: init-config
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Generating application configuration..."
      cat > /config/app.conf <<EOF
      database_host=db.example.com
      database_port=5432
      app_version=1.0.0
      EOF
      echo "Configuration generated"
    volumeMounts:
    - name: config
      mountPath: /config
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config
      mountPath: /etc/app
    command:
    - sh
    - -c
    - |
      echo "Application starting..."
      cat /etc/app/app.conf
      cat /etc/app/db-status
      nginx -g 'daemon off;'
  volumes:
  - name: config
    emptyDir: {}
