apiVersion: v1
kind: Pod
metadata:
  name: memory-limit-demo
  labels:
    app: memory-test
    kubernetes.courselabs.co: pods
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "200m"
    command:
    - stress
    args:
    - --vm
    - "1"
    - --vm-bytes
    - "150M"  # Exceeds 100Mi limit - will be OOMKilled
    - --vm-hang
    - "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-limit-demo
  labels:
    app: cpu-test
    kubernetes.courselabs.co: pods
spec:
  containers:
  - name: cpu-hog
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "200m"  # CPU will be throttled, not killed
    command:
    - stress
    args:
    - --cpu
    - "2"
    - --timeout
    - "60s"
