apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  labels:
    kubernetes.courselabs.co: pods
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa
  labels:
    app: sa-demo
    kubernetes.courselabs.co: pods
spec:
  serviceAccountName: my-service-account
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Service Account Information ==="
      echo "Service Account: $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
      echo "Token present: $(test -f /var/run/secrets/kubernetes.io/serviceaccount/token && echo 'YES' || echo 'NO')"
      echo ""
      echo "Mounted Service Account Files:"
      ls -la /var/run/secrets/kubernetes.io/serviceaccount/
      sleep 3600
---
# Example with automountServiceAccountToken disabled
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-sa
  labels:
    kubernetes.courselabs.co: pods
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-no-sa-token
  labels:
    app: restricted-demo
    kubernetes.courselabs.co: pods
spec:
  serviceAccountName: restricted-sa
  automountServiceAccountToken: false  # Can also disable at pod level
  containers:
  - name: app
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "=== Checking Service Account Token ==="
      if [ -d /var/run/secrets/kubernetes.io/serviceaccount/ ]; then
        echo "Service account directory exists"
        ls -la /var/run/secrets/kubernetes.io/serviceaccount/ || echo "But is empty"
      else
        echo "No service account token mounted"
      fi
      sleep 3600
---
# Example using service account to access Kubernetes API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-access-sa
  labels:
    kubernetes.courselabs.co: pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  labels:
    kubernetes.courselabs.co: pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  labels:
    kubernetes.courselabs.co: pods
subjects:
- kind: ServiceAccount
  name: api-access-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-api-access
  labels:
    app: api-demo
    kubernetes.courselabs.co: pods
spec:
  serviceAccountName: api-access-sa
  containers:
  - name: app
    image: alpine:latest
    command:
    - sh
    - -c
    - |
      # Install curl
      apk add --no-cache curl

      echo "=== Accessing Kubernetes API with Service Account ==="

      # Get service account token
      TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

      # Kubernetes API server
      APISERVER=https://kubernetes.default.svc

      # List pods in namespace (allowed by Role)
      echo ""
      echo "Listing pods in namespace $NAMESPACE:"
      curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
           --header "Authorization: Bearer $TOKEN" \
           $APISERVER/api/v1/namespaces/$NAMESPACE/pods | grep '"name"' | head -5

      echo ""
      echo "Attempting to list services (should fail - not in Role):"
      curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
           --header "Authorization: Bearer $TOKEN" \
           $APISERVER/api/v1/namespaces/$NAMESPACE/services

      sleep 3600
