apiVersion: v1
kind: Pod
metadata:
  name: web-with-sidecar
  labels:
    app: web
    pattern: sidecar
    kubernetes.courselabs.co: pods
spec:
  containers:
  - name: web-app
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  - name: log-processor
    image: busybox:latest
    command:
    - sh
    - -c
    - |
      echo "Log processor sidecar started"
      while true; do
        # Process nginx access logs
        if [ -f /logs/access.log ]; then
          echo "=== Processing logs at $(date) ==="
          # Count requests in last 10 seconds
          tail -n 100 /logs/access.log | wc -l
        fi
        sleep 10
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /logs
  volumes:
  - name: shared-logs
    emptyDir: {}
