# Exercise 4: Security Hardening
#
# Create a security-hardened Pod following best practices:
# - Runs as non-root user (UID 1000)
# - Uses read-only root filesystem
# - Drops all capabilities except NET_BIND_SERVICE
# - Uses a custom service account
# - Includes resource limits
#
# Requirements:
# - Pod name: secure-web
# - Image: nginx:alpine
# - Port: 8080 (non-privileged)
# - Service Account: secure-sa (create it)
# - Security: non-root, read-only filesystem, minimal capabilities
# - Resource requests: 64Mi memory, 100m CPU
# - Resource limits: 128Mi memory, 200m CPU
# - Add labels: app=secure-web, kubernetes.courselabs.co=pods

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-sa
  labels:
    kubernetes.courselabs.co: pods
automountServiceAccountToken: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-nginx-config
  labels:
    kubernetes.courselabs.co: pods
data:
  default.conf: |
    server {
      listen 8080;  # Non-privileged port
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-web
  labels:
    app: secure-web
    kubernetes.courselabs.co: pods
spec:
  serviceAccountName: secure-sa
  automountServiceAccountToken: false

  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault

  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 8080

    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE

    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"

    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5

    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: cache
      mountPath: /var/cache/nginx
    - name: run
      mountPath: /var/run
    - name: tmp
      mountPath: /tmp

  volumes:
  - name: nginx-config
    configMap:
      name: secure-nginx-config
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}
  - name: tmp
    emptyDir: {}
