# Basic ServiceAccount with RBAC configuration
# Demonstrates: ServiceAccount creation, Role with basic permissions, RoleBinding, and Pod usage
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basic-app
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
---
# Role granting permissions to list and get pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding connecting ServiceAccount to Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic-app-pod-reader
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: basic-app
  namespace: default
---
# Pod using the ServiceAccount
apiVersion: v1
kind: Pod
metadata:
  name: basic-app-pod
  namespace: default
  labels:
    app: basic-app
    kubernetes.courselabs.co: rbac-ckad
spec:
  serviceAccountName: basic-app
  containers:
  - name: app
    image: nginx:alpine
    command: ["sleep", "3600"]
  restartPolicy: Never
