# Exercise 1: Multi-Namespace Application
# Three-tier application across namespaces

# Database namespace
apiVersion: v1
kind: Namespace
metadata:
  name: database

---
# Database ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: db-quota
  namespace: database
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"

---
# MySQL Pod
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: database
  labels:
    app: mysql
    tier: database
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "rootpassword"
    - name: MYSQL_DATABASE
      value: "appdb"
    - name: MYSQL_USER
      value: "appuser"
    - name: MYSQL_PASSWORD
      value: "apppassword"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: database
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP

---
# API namespace
apiVersion: v1
kind: Namespace
metadata:
  name: api

---
# API ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: api-quota
  namespace: api
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"

---
# ConfigMap with database connection info
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: api
data:
  DB_HOST: mysql.database.svc.cluster.local
  DB_PORT: "3306"
  DB_NAME: appdb

---
# Secret with database credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: api
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASSWORD: apppassword

---
# API Pod
apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: api
  labels:
    app: api
    tier: backend
spec:
  containers:
  - name: api
    image: nginx:alpine
    ports:
    - containerPort: 80
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_PORT
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASSWORD
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"

---
# API Service
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
# Web namespace
apiVersion: v1
kind: Namespace
metadata:
  name: web

---
# Web ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: web-quota
  namespace: web
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"

---
# ConfigMap with API connection info
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: web
data:
  API_URL: http://api.api.svc.cluster.local
  API_PORT: "80"

---
# Web frontend Pod
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: web
  labels:
    app: web
    tier: frontend
spec:
  containers:
  - name: web
    image: nginx:alpine
    ports:
    - containerPort: 80
    env:
    - name: API_URL
      valueFrom:
        configMapKeyRef:
          name: api-config
          key: API_URL
    - name: API_PORT
      valueFrom:
        configMapKeyRef:
          name: api-config
          key: API_PORT
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"

---
# Web Service
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
