# LimitRange with default container limits
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container

---
# LimitRange with min/max constraints
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-limits
  namespace: default
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container

---
# LimitRange with all constraint types
apiVersion: v1
kind: LimitRange
metadata:
  name: comprehensive-limits
  namespace: default
spec:
  limits:
  - max:
      cpu: "4"
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    maxLimitRequestRatio:
      cpu: "4"
      memory: "2"
    type: Container
  - max:
      storage: 10Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim

---
# Namespace with LimitRange
apiVersion: v1
kind: Namespace
metadata:
  name: limitrange-demo

---
# LimitRange for the demo namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limits
  namespace: limitrange-demo
spec:
  limits:
  - default:
      cpu: 300m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container
