# Namespace for ServiceAccount demo
apiVersion: v1
kind: Namespace
metadata:
  name: sa-demo

---
# Custom ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: sa-demo

---
# Pod using custom ServiceAccount
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa
  namespace: sa-demo
spec:
  serviceAccountName: app-service-account
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80

---
# Role with permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: sa-demo
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---
# RoleBinding to connect ServiceAccount to Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: sa-demo
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: sa-demo
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
# Pod with automountServiceAccountToken disabled
apiVersion: v1
kind: Pod
metadata:
  name: pod-no-token
  namespace: sa-demo
spec:
  serviceAccountName: app-service-account
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx:alpine

---
# Pod with custom token mount path
apiVersion: v1
kind: Pod
metadata:
  name: pod-custom-mount
  namespace: sa-demo
spec:
  serviceAccountName: app-service-account
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "ls -la /var/run/secrets/kubernetes.io/serviceaccount && sleep 3600"]
    volumeMounts:
    - name: token-volume
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
  volumes:
  - name: token-volume
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 7200
