# Exercise 2: Resource Management and QoS Classes
# Three deployments demonstrating each QoS class

# 1. Guaranteed QoS - requests equal limits
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guaranteed-app
  labels:
    kubernetes.courselabs.co: productionizing
    qos: guaranteed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guaranteed-app
  template:
    metadata:
      labels:
        app: guaranteed-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
# 2. Burstable QoS - requests less than limits
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burstable-app
  labels:
    kubernetes.courselabs.co: productionizing
    qos: burstable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: burstable-app
  template:
    metadata:
      labels:
        app: burstable-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
# 3. BestEffort QoS - no resources specified
apiVersion: apps/v1
kind: Deployment
metadata:
  name: besteffort-app
  labels:
    kubernetes.courselabs.co: productionizing
    qos: besteffort
spec:
  replicas: 2
  selector:
    matchLabels:
      app: besteffort-app
  template:
    metadata:
      labels:
        app: besteffort-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        # No resources specified
---
# Stress test pod to create memory pressure
apiVersion: v1
kind: Pod
metadata:
  name: memory-pressure
  labels:
    kubernetes.courselabs.co: productionizing
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "1G"
    - "--vm-hang"
    - "1"
    resources:
      requests:
        memory: "1Gi"
      limits:
        memory: "1Gi"
