apiVersion: v1
kind: Namespace
metadata:
  name: exercise1-fixed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: exercise1-fixed
data:
  database_url: "postgres://db.example.com:5432"
  api_key: "config-api-key-123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: exercise1-fixed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web  # FIXED: Matches pod labels
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database_url  # FIXED: Correct key name
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: exercise1-fixed
spec:
  selector:
    app: web
  ports:
  - port: 80       # FIXED: Port matches container port
    targetPort: 80
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: exercise1-fixed
spec:
  hard:
    requests.cpu: "500m"    # FIXED: Sufficient for deployment
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
