apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pending-pvc-claim-fixed
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Reduced to a reasonable size
  # Use the default storage class or one that exists in your cluster
  # To check: kubectl get storageclass
  # storageClassName: standard  # Uncomment and use your cluster's storage class
---
apiVersion: v1
kind: Pod
metadata:
  name: pending-pvc-pod-fixed
  labels:
    app: troubleshooting-demo
    scenario: pending
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pending-pvc-claim-fixed
