apiVersion: v1
kind: Pod
metadata:
  name: memory-optimized
  labels:
    app: troubleshooting-demo
    scenario: performance
spec:
  containers:
  - name: app
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - |
      # Properly sized memory usage
      apt-get update && apt-get install -y stress-ng
      # Use less memory and limited duration
      stress-ng --vm 1 --vm-bytes 100M --vm-hang 0 --timeout 300s
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"  # Increased to accommodate workload
      limits:
        cpu: "200m"
        memory: "512Mi"  # Sufficient headroom to prevent OOM
