apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  labels:
    kubernetes.courselabs.co: affinity-ckad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
        kubernetes.courselabs.co: affinity-ckad
    spec:
      containers:
      - name: redis
        image: redis:6-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
