# Example: Canary Deployment Using Partitions
# Use case: Test new version on subset of Pods before full rollout
# Benefit: Gradual rollout with ability to verify changes on higher-ordinal Pods

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  clusterIP: None
  selector:
    app: api
  ports:
  - port: 8080
    name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-service
spec:
  serviceName: api-service
  replicas: 5
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 3  # Only Pods with ordinal >= 3 will be updated
                    # Pods 0, 1, 2 stay on old version (safe canary)
                    # Pods 3, 4 get new version (canary instances)
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        version: v2  # New version label
    spec:
      containers:
      - name: api
        image: nginx:1.25-alpine  # New version
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: VERSION
          value: "v2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: nginx-config
          optional: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

---
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            return 200 "Pod: $hostname\n";
            add_header Content-Type text/plain;
        }
    }
