# Database Tier - Challenge
# Requirements: SSD nodes, tolerate database taint, spread across nodes

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    tier: database
    app: postgres
spec:
  serviceName: database
  replicas: 2
  selector:
    matchLabels:
      tier: database
      app: postgres
  template:
    metadata:
      labels:
        tier: database
        app: postgres
    spec:
      nodeSelector:
        disk: ssd
      tolerations:
      - key: "database"
        operator: "Equal"
        value: "critical"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                tier: database
            topologyKey: kubernetes.io/hostname
      containers:
      - name: postgres
        image: postgres:14-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "challenge"
        - name: POSTGRES_DB
          value: "appdb"
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    tier: database
spec:
  clusterIP: None
  selector:
    tier: database
  ports:
  - port: 5432
    targetPort: 5432
