# Secret management with restricted RBAC
# Demonstrates: Fine-grained secret access control
# Create test secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
type: Opaque
stringData:
  db-password: "MySecureDBPassword123"
  api-token: "api-token-xyz"
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secrets
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
type: Opaque
stringData:
  admin-password: "SuperSecretAdminPass"
---
# Role with restricted secret permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
rules:
# List all secrets (but can't read contents without 'get')
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
# Read specific secret only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["app-secrets"]
  verbs: ["get"]
# Update/patch specific secret only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["app-secrets"]
  verbs: ["update", "patch"]
---
# ServiceAccount for app secret management
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-sa
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
- kind: ServiceAccount
  name: secret-manager-sa
  namespace: default
---
# Example: Role for secret creation (separate from reading)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator
  namespace: default
  labels:
    kubernetes.courselabs.co: rbac-ckad
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]  # Only create, no read/update/delete
